name: Build and Test

on: [push]

japs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v

    - name: Install GCC
      run: sudo apt-get install -y gcc
    - name: Compile Hello World
      run: gcc hello.c -o hello
    - name: Run Hello World
      run: ./hello 